server:
  port: 8888

app:
  api-prefix: /api/v1

  services:
    identity:
      url: ${IDENTITY_SERVICE_URL:http://localhost:8443/identity}

    chat:
      url: ${CHAT_SERVICE_URL:http://localhost:8085/chat}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: demo_identity_service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8443/identity}
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        - id: chat_service
          uri: ${CHAT_SERVICE_URL:http://localhost:8085/chat}
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2