server:
  port: 8085
  servlet:
    context-path: /chat
spring:

  application:
    name: chat-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mydb}
      auto-index-creation: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vector_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver


  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com/v1beta/openai
        options:
          model: gemini-2.5-flash-lite

      embedding:
        base-url: https://generativelanguage.googleapis.com/v1beta/openai
        embeddings-path: /embeddings
        options:
          model: gemini-embedding-001

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE
        dimensions: 768
        table-name: vector_store
        initialize-schema: true
        datasource:
          url: ${VECTOR_DB_CONNECTION:jdbc:postgresql://localhost:5432/vector_db}
          username: ${VECTOR_DB_USERNAME:postgres}
          password: ${VECTOR_DB_PASSWORD:123456}
          driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.ai.openai: DEBUG
    org.springframework.web.client: DEBUG
app:
  services:
    profile:
      url: ${PROFILE_SERVICE_URL:http://localhost:8443/identity}
    identity:
      url: ${IDENTITY_SERVICE_URL:http://localhost:8443/identity}
