spring.application.name=demo-identity-service
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=DEBUG


# application.properties
stripe.secret.key=sk_test_51Rpl8wRqw7xssaCVRT3M6ZNmg8pgGtwP8QLSazRrhRklvGV8GmMvF7SrN9SN47ora4MQG2Wf13AgOuHMkkQEgg9w00yVcHyF6F

#####
#
# HTTPS configuration
#
#####

# Server web port
server.port=8443

# Enable HTTPS support (only accept HTTPS requests)
#server.ssl.enabled=true

# Alias that identifies the key in the key store
#server.ssl.key-alias=luv2code

# Keystore location
#server.ssl.key-store=classpath:luv2code-keystore.p12

# Keystore password
#server.ssl.key-store-password=secret

# Keystore format
#server.ssl.key-store-type=PKCS12
